services:
    crevillo.ezsocialloginbundle.oauth_aware.user_provider.service:
        class: Crevillo\EzSocialLoginBundle\Security\EzSocialUserProvider
        arguments:
            - '@ezpublish.api.inner_repository'
