parameters:
    # override default linkedin resource owner
    hwi_oauth.resource_owner.linkedin.class: Crevillo\EzSocialLoginBundle\OAuth\ResourceOwner\LinkedinResourceOwner

services:
    crevillo.ezsocialloginbundle.oauth_aware.user_provider.service:
        class: Crevillo\EzSocialLoginBundle\Security\EzSocialUserProvider
        arguments:
            - '@crevillo.ezsocialloginbundle.user_manager'

    crevillo.ezsocialloginbundle.user_manager:
        class: Crevillo\EzSocialLoginBundle\Core\EzSocialLoginUserManager
        arguments:
            - '@ezpublish.api.inner_repository'
